INHERIT: docs_template/mkdocs.yml

docs_dir: 'docs'

repo_name: Centurion ERP UI
repo_url: https://github.com/nofusscomputing/centurion_erp_ui
edit_uri: '/edit/development/docs/'
theme: 
  icon:
    repo: fontawesome/brands/github


nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Centurion ERP:

    - projects/centurion_erp/index.md

  - Centurion User Interface:

    - projects/centurion_user_interface/index.md

    - projects/centurion_user_interface/development.md

    - projects/centurion_user_interface/metadata.md

    - projects/centurion_user_interface/navigation.md

    - projects/centurion_user_interface/setup.md

    - projects/centurion_user_interface/url.md

    - API:

      - projects/centurion_user_interface/api/index.md

    - Components:

      - projects/centurion_user_interface/components/comment.md

    - Fields:

      - projects/centurion_user_interface/fields/markdown.md

    - Layouts:

      - projects/centurion_user_interface/layout/index.md

      - projects/centurion_user_interface/layout/list.md

      - projects/centurion_user_interface/layout/ticket.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

