server {

    listen 80;

    location = /favicon.ico { access_log off; log_not_found off; }

    root   /usr/share/nginx/html;

    # location / {

    #     include proxy_params;

    #     root   /usr/share/nginx/html;
    #     index  index.html;

    # }
    location / {

        try_files $uri /index.html;

    }


    # immutable JS chunks
    location ~* ^/assets/js/.*\.[a-f0-9]+\.js$ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    # Fonts static caching
    location ~* ^/assets/fonts/.*\.[a-f0-9]+\.(png|jpg|jpeg|gif|svg|woff2|woff|ttf)$ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    # Icons static caching
    location ~* ^/assets/icons/.*\.[a-f0-9]+\.svg$ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    # Images static caching
    location ~* ^/assets/images/.*\.[a-f0-9]+\.(png|jpg|jpeg|gif|svg)$ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    # Styles / CSS chunks
    location ~* ^/assets/styles/.*\.[a-f0-9]+\.css$ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }


    location /mock/ {
        default_type application/json;

        add_header Access-Control-Allow-Origin $mock_cors_origin always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-CSRFToken" always;
        add_header Access-Control-Allow-Credentials "true" always;

        # Some wizardry as nginx will not allow HTTP/OPTIONS requests.
        # to cater for this, HTTP/GET proxy the requests back to `self`
        # suffixing the filename request. `$uri/$request_method.json`
        if ($request_method = OPTIONS) {

            error_page 405 = @mock-app-options;

        }

        try_files $uri/$request_method.json $uri @app =404;

    }


    location @mock-app-options {

        proxy_method GET;
        proxy_pass http://127.0.0.1$request_uri/OPTIONS.json;

    }



    location /assets/ {
        # Path to your static files
        alias /usr/share/nginx/html/assets/;
    }


}